framework:
    messenger:
        transports:
            provisioning:
                dsn: '%env(MESSENGER_PROVISIONING_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: infratak.provisioning
                    queues:
                        infratak.provisioning: ~
                retry_strategy:
                    max_retries: 5
                    delay: 10000
                    multiplier: 1.5
                    max_delay: 30000
            projection:
                dsn: '%env(MESSENGER_PROJECTION_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: infratak.projection
                    queues:
                        infratak.projection: ~
                retry_strategy:
                    max_retries: 5
                    delay: 2000
                    multiplier: 2
                    max_delay: 10000

        routing:
            App\Message\CreateServerMessage: provisioning
            App\Message\DeleteServerMessage: provisioning
            App\Message\DiagnoseServerMessage: provisioning
            App\Message\ServerProjectionMessage: projection

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
