
services:
  nginx:
    ports:
      - "8080:80"

  php:
    environment:
      APP_ENV: dev
      APP_DEBUG: "1"
      TZ: Europe/Warsaw

  worker_provisioning:
    environment:
      APP_ENV: dev
      APP_DEBUG: "1"
      TZ: Europe/Warsaw

  worker_projection:
    environment:
      APP_ENV: dev
      APP_DEBUG: "1"
      TZ: Europe/Warsaw

  mariadb:
    ports:
      - "3306:3306"
    environment:
      TZ: Europe/Warsaw

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
